language: node_js
node_js:
  - 10.16.0

jobs:
  include:
    - stage: "Build"
      name: "Compile and lint"
      script: yarn build:prod
    - stage: "Test"
      name: "Run unit tests"
      script: yarn test:unit
    - stage: "Release"
      name: "Build binary for OSX"
      script: yarn release:mac:ci

