language: node_js
node_js:
  - 10.16.0

os: osx

jobs:
  include:
    - stage: "Bundle"
      name: "Bundle and lint code"
      script: yarn bundle:prod
    - stage: "Test"
      name: "Run unit tests"
      script: yarn test:unit
    - stage: "Release"
      name: "Build binaries"
      script: yarn bundle:prod && yarn release

