language: node_js
node_js:
  - 10.16.0

os: osx

jobs:
  include:
    - stage: "Test"
      name: "Run unit tests"
      script: yarn test:unit
    - stage: "Release"
      name: "Create bundle and build binary"
      if: branch = master AND type = push
      script: yarn bundle:prod && yarn release
      if: branch != master OR type != push
      script: yarn bundle:prod && yarn test-release:mac

