language: node_js
node_js:
  - 10.16.0

os:
  - osx
  - windows
matrix:
  include:
    - stage: "Test"
      name: "Run unit tests"
      os: osx
      script: yarn test:unit
    - stage: "Release"
      name: "Create bundle and build binary"
      if: branch = master AND type = push
      script: yarn bundle:prod && yarn release
      if: branch != master OR type != push
      os: osx
      script: yarn bundle:prod && yarn test-release:mac
    - stage: "Test"
      name: "Run unit tests"
      os: windows
      script: yarn test:unit
    - stage: "Release"
      name: "Create bundle and build binary"
      if: branch = master AND type = push
      script: yarn bundle:prod && yarn release
      if: branch != master OR type != push
      os: windows
      script: yarn bundle:prod && yarn test-release:mac

